import type {Metadata} from "next";
import {fontOutfit} from "@repo/ui/fonts";
import Providers from "./providers";
import "@repo/ui/styles/css/base.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fontOutfit.variable} ${fontOutfit.className}`}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
