import type { Metadata } from "next";
import { outfit } from "@repo/fonts";
import Providers from "./providers";
import "../../../styles/css/base.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={outfit.variable}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
