// Code generated by Wire. DO NOT EDIT.
// Manually maintained to reflect shared AuthService/AuthHandler architecture.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"Backend/internal/handlers"
	"Backend/internal/repository"
	"Backend/internal/service"
	"Backend/pkg/sms"
	"Backend/pkg/socket"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*App, error) {
	// ── Socket Hub ────────────────────────────────────────────────────────────
	hub := socket.NewHub()

	// ── Repositories ─────────────────────────────────────────────────────────
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	otpRepository := repository.NewOTPRepository(db)
	customerRepository := repository.NewCustomerRepository(db)
	quotationRepository := repository.NewQuotationRepository(db)
	leadRepository := repository.NewLeadRepository(db)
	dashboardRepository := repository.NewDashboardRepository(db)
	rewardRepository := repository.NewRewardRepository(db)
	planRepository := repository.NewPlanRepository(db)

	// ── Services ──────────────────────────────────────────────────────────────
	smsService := sms.NewSMSService()
	authService := service.NewAuthService(userRepository, sessionRepository, rewardRepository)
	adminService := service.NewAdminService(userRepository, sessionRepository)
	userService := service.NewUserService(userRepository)
	sessionService := service.NewSessionService(sessionRepository)
	otpService := service.NewOTPService(otpRepository, smsService)
	customerService := service.NewCustomerService(customerRepository, rewardRepository)
	quotationService := service.NewQuotationService(quotationRepository, customerRepository)
	leadService := service.NewLeadService(leadRepository, customerRepository)
	dashboardService := service.NewDashboardService(dashboardRepository)
	planService := service.NewPlanService(planRepository, rewardRepository)

	// ── Handlers ──────────────────────────────────────────────────────────────
	authHandler := handlers.NewAuthHandler(authService, otpService, sessionService, hub)
	adminHandler := handlers.NewAdminHandler(adminService)
	userHandler := handlers.NewUserHandler(userService, leadService, quotationService)
	customerHandler := handlers.NewCustomerHandler(customerService)
	quotationHandler := handlers.NewQuotationHandler(quotationService, hub)
	leadHandler := handlers.NewLeadHandler(leadService, hub)
	dashboardHandler := handlers.NewDashboardHandler(dashboardService)
	planHandler := handlers.NewPlanHandler(planService)
	wsHandler := handlers.NewWsHandler(hub)

	app := NewApp(authHandler, adminHandler, userHandler, customerHandler, quotationHandler, leadHandler, dashboardHandler, planHandler, wsHandler, hub)
	return app, nil
}
