-- Seed default plans (clear first to allow idempotent re-runs)
DELETE FROM plan;

INSERT INTO plan ("planType","name","description","category","tier","billingCycle","price","isFree","isPopular","featureJson","isActive") VALUES
-- ── Individual Monthly ──────────────────────────────────────────────────────
('individual_silver_monthly','Silver','Basic travel access for individuals','individual','silver','monthly',0.00,TRUE,FALSE,'["Basic travel search","Up to 3 bookings/month","Email support","Standard pricing","1 device access","Trip history (3 months)","Basic notifications","Profile management","Community forum access"]',TRUE),
('individual_gold_monthly','Gold','Best for frequent individual travellers','individual','gold','monthly',499.00,FALSE,TRUE,'["Advanced travel search","Unlimited bookings","Priority support","Exclusive deals up to 20% off","3 device access","Trip history (1 year)","Smart notifications","Group travel tools","Early access to offers"]',TRUE),
('individual_platinum_monthly','Platinum','All-inclusive premium individual plan','individual','platinum','monthly',999.00,FALSE,FALSE,'["Premium travel search","Unlimited bookings + concierge","24/7 dedicated support","Exclusive deals up to 40% off","Unlimited device access","Full trip history","AI trip suggestions","Corporate billing","VIP lounge access"]',TRUE),
-- ── Individual Yearly ───────────────────────────────────────────────────────
('individual_silver_yearly','Silver','Basic travel access for individuals','individual','silver','yearly',0.00,TRUE,FALSE,'["Basic travel search","Up to 3 bookings/month","Email support","Standard pricing","1 device access","Trip history (3 months)","Basic notifications","Profile management","Community forum access"]',TRUE),
('individual_gold_yearly','Gold','Best for frequent individual travellers','individual','gold','yearly',4188.00,FALSE,TRUE,'["Advanced travel search","Unlimited bookings","Priority support","Exclusive deals up to 20% off","3 device access","Trip history (1 year)","Smart notifications","Group travel tools","Early access to offers"]',TRUE),
('individual_platinum_yearly','Platinum','All-inclusive premium individual plan','individual','platinum','yearly',8388.00,FALSE,FALSE,'["Premium travel search","Unlimited bookings + concierge","24/7 dedicated support","Exclusive deals up to 40% off","Unlimited device access","Full trip history","AI trip suggestions","Corporate billing","VIP lounge access"]',TRUE),
-- ── Corporate Monthly ───────────────────────────────────────────────────────
('corporate_silver_monthly','Silver','Team travel essentials','corporate','silver','monthly',999.00,FALSE,FALSE,'["Business travel search","Up to 10 bookings/month","Email support","Corporate pricing","5 team seats","Trip history (6 months)","Approval workflows","Expense tracking","GST invoice support"]',TRUE),
('corporate_gold_monthly','Gold','Best for growing travel businesses','corporate','gold','monthly',1999.00,FALSE,TRUE,'["Advanced business search","Unlimited bookings","Priority support","Exclusive deals up to 25% off","15 team seats","Trip history (2 years)","Smart approval workflows","Advanced expense reports","Dedicated account manager"]',TRUE),
('corporate_platinum_monthly','Platinum','Enterprise-grade travel management','corporate','platinum','monthly',3999.00,FALSE,FALSE,'["Premium business search","Unlimited bookings + concierge","24/7 dedicated support","Exclusive deals up to 45% off","Unlimited team seats","Full audit history","Custom workflows","API access","White-label options"]',TRUE),
-- ── Corporate Yearly ────────────────────────────────────────────────────────
('corporate_silver_yearly','Silver','Team travel essentials','corporate','silver','yearly',8388.00,FALSE,FALSE,'["Business travel search","Up to 10 bookings/month","Email support","Corporate pricing","5 team seats","Trip history (6 months)","Approval workflows","Expense tracking","GST invoice support"]',TRUE),
('corporate_gold_yearly','Gold','Best for growing travel businesses','corporate','gold','yearly',16788.00,FALSE,TRUE,'["Advanced business search","Unlimited bookings","Priority support","Exclusive deals up to 25% off","15 team seats","Trip history (2 years)","Smart approval workflows","Advanced expense reports","Dedicated account manager"]',TRUE),
('corporate_platinum_yearly','Platinum','Enterprise-grade travel management','corporate','platinum','yearly',33588.00,FALSE,FALSE,'["Premium business search","Unlimited bookings + concierge","24/7 dedicated support","Exclusive deals up to 45% off","Unlimited team seats","Full audit history","Custom workflows","API access","White-label options"]',TRUE);
