ALTER TABLE plan
  ADD COLUMN IF NOT EXISTS "name"         VARCHAR,
  ADD COLUMN IF NOT EXISTS "description"  TEXT,
  ADD COLUMN IF NOT EXISTS "category"     VARCHAR DEFAULT 'individual',
  ADD COLUMN IF NOT EXISTS "tier"         VARCHAR,
  ADD COLUMN IF NOT EXISTS "billingCycle" VARCHAR DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS "price"        DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "isFree"       BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "isPopular"    BOOLEAN DEFAULT FALSE;
