// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"internal/handlers"
	"internal/repository"
	"internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*App, error) {
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	userService := service.NewUserService(userRepository, sessionRepository)
	sessionService := service.NewSessionService(sessionRepository)
	authHandler := handlers.NewAuthHandler(userService, sessionService)
	app := NewApp(authHandler)
	return app, nil
}
