// Code generated by Wire. DO NOT EDIT.
// Manually updated to reflect shared AuthService/AuthHandler architecture.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"Backend/internal/handlers"
	"Backend/internal/repository"
	"Backend/internal/service"
	"Backend/pkg/sms"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp(db *gorm.DB) (*App, error) {
	// ── Repositories ──────────────────────────────────────────────────────
	userRepository := repository.NewUserRepository(db)
	sessionRepository := repository.NewSessionRepository(db)
	otpRepository := repository.NewOTPRepository(db)
	customerRepository := repository.NewCustomerRepository(db)
	quotationRepository := repository.NewQuotationRepository(db)
	leadRepository := repository.NewLeadRepository(db)
	dashboardRepository := repository.NewDashboardRepository(db)

	// ── Services ──────────────────────────────────────────────────────────
	smsService := sms.NewSMSService()
	authService := service.NewAuthService(userRepository, sessionRepository)
	adminService := service.NewAdminService(userRepository, sessionRepository)
	userService := service.NewUserService(userRepository)
	sessionService := service.NewSessionService(sessionRepository)
	otpService := service.NewOTPService(otpRepository, smsService)
	customerService := service.NewCustomerService(customerRepository)
	quotationService := service.NewQuotationService(quotationRepository, customerRepository)
	leadService := service.NewLeadService(leadRepository, customerRepository)
	dashboardService := service.NewDashboardService(dashboardRepository)

	// ── Handlers ──────────────────────────────────────────────────────────
	authHandler := handlers.NewAuthHandler(authService, otpService, sessionService)
	adminHandler := handlers.NewAdminHandler(adminService)
	userHandler := handlers.NewUserHandler(userService)
	customerHandler := handlers.NewCustomerHandler(customerService)
	quotationHandler := handlers.NewQuotationHandler(quotationService)
	leadHandler := handlers.NewLeadHandler(leadService)
	dashboardHandler := handlers.NewDashboardHandler(dashboardService)

	app := NewApp(authHandler, adminHandler, userHandler, customerHandler, quotationHandler, leadHandler, dashboardHandler)
	return app, nil
}
