import type {Metadata} from "next";
import {fontOutfit} from "@repo/ui/fonts/fonts";
import Providers from "./providers";
import "@repo/ui/styles/css/base.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "User App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontOutfit.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
